### ISSUE TITLE
Missing stderr output for GitError 

### ISSUE THREAD

**Issue by danielhaap83** [keirlawson/rusty-git#7]
If git command fails the stderr message is not part of the message although it is available.

Example: Checkout invalid tag
```rust
repo.switch_branch(&BranchName::from_str("tag/some_tag")?)?;
```

Console output:
```sh
Error: git failed with the following stdout:
```

Expected console output:
```sh
Error: git failed with the following stdout: stderr: error: pathspec 'tag/some_tag' did not match any file(s) known to git
```

**Comment by danielhaap83** [comment]
I cannot create a new branch? Solution could be in error.rs
```rust
...
    #[error("git failed with the following stdout: {stdout} stderr: {stderr}")]
    GitError{
        stdout: String,
        stderr: String
    },
...
```

**Comment by keirlawson** [comment]
Thanks for reporting and sorry for the delay in replying, your suggested fix looks good to me, to create a PR you will need to fork the repo and then create a PR from your fork.

**Comment by danielhaap83** [comment]
Thank you. Linked the PR
